
---
# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinodapp
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vinodapp
  template:
    metadata:
      labels:
        app: vinodapp
    spec:
      containers:
      - name: vinodapp
        image: vinodkhathi/vinodapp:v4
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/vinodappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Test@123
---
# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: vinodapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: vinodapp
